# Generated by Django 5.1.6 on 2025-03-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
