# Generated by Django 5.1.6 on 2025-03-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_review_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
